config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'posts#index', as: 'home'
get 'about' => 'pages#about', as: 'about'

resources :posts do
	resources :comments
end
resources :twiits do
	collection {post :import}	


end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	validates :title, presence: true,
						length: {minimum: 5}
	belongs_to :user					
end

app/models/twiit.rb
class Product < ActiveRecor::BAse
	attr_accessible :message, :date

	def self.to_csv(options = {})
		CSV.Generate(options) do |CSV|
			csv <<column_names
			all.each do |product|
				csv << product.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Product.create! row.to_hash
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	#http_basic_authenticate_with name: "migzu", password:"1234", only: [:destroy]
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	def destroy 
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
# en tiedä miksi ei toimi ylläolevalla koodilla :D selvitellään...
#def show 
#		@post = Post.find(params[:post_id])
#		@comment = @post.comments.find(params[:id])
#		@comment.destroy
#		redirect_to post_path(@post)
#	end

	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/concerns/twiits_controller.rb
class TwiitsController < ApplicationController
	def index
		@twiits = twiit.order(:message)
		respond_to do |format|
			format.html
			format.csv { send_data @twiits.to_csv}
			format.xls # { send_data @twiits.to_csv(col_spe: "\t")}
		end
	end

	def import
		Twiits.import(params[:file])
		redirect_to root_url, notice: "Information imported!"
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us';
		@content = 'This is the about page';

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#http_basic_authenticate_with name: "migzu", password:"1234", except: [:index, :show]
	before_action :authenticate_user!, except: [:index, :show]
	#before_filter :correct_user!, only: [:edit, :update, :show]

	def index 
		@posts =Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = current_user.posts.build
	end

	def create
		#render plain: params[:post].inspect
		#ylläoleva oli testinä postauksien tallentamista varten
		@post = current_user.posts.build(post_params)
		
		if(@post.save)
		redirect_to @post
		else 
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else 
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end
		

	private def post_params
		params.require(:post).permit(:title, :body)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
	<div class="well">
	<p><strong><%= comment.username %></strong>: <%= comment.body %>
	<%= link_to '[X]', [comment.post, comment],
				method: :delete,
				data: { confirm: 'Are you sure?' } %></p>
	</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for ([@post, @post.comments.build]) do |f| %>			
	<p>
		<%= f.label :username %><br>
		<%= f.text_field(:username, {:class => 'form-control'}) %>
	</p>
	<p>
	<%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'})%>
	</p>
	<p>
	<%= f.submit({:class => 'form-control' })%>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
     <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'  %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> 
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">SimpleBlog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
            <% if user_signed_in? %>
            <li>Logged in as <strong><%= current_user.email %> </strong></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create Post", new_post_path %></li>
           <% if user_signed_in? %>
            
            <%= link_to "Edit profile", edit_user_registration_path %> or
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <% else %>
            
            <%= link_to "Sign Up", new_user_registration_path %> or
            <%= link_to "Sign In", new_user_session_path %> 
            <% end %> 

            <!--Tässä kommentoitu pätkä signupin alkuperäisestä muodosta josta väriä ei vaihdettu
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            -->
            

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<div class="container">




<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



  <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

<!-- tästä alaspäin uutta koodia-->

<table id ="Twiits">
<tr>
	<th>Message</th>
	<th> Date </th>
	</tr>

<% @twiits.each do |twiit| %>
<tr>
	<th> <%= twiit.name %> </th>
	<th> <%= twiit.released_on.strftime("%B %e, %Y") %> </th>
	</tr>
<% end %>
</table>	




<h1>Twitter feed</h1>
<h2>Import Information</h2>

<%= form_tag import_twiits_path, multipart: true do %>
	<%= file_field_tag :file %>

	<%= submit_tag "Import" %>

<% end %>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %> 
		<% @post.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>	
	<p>
	<%= f.label :title %> <br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
	<%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1>Here are listed all the blog posts</h1>
<% @posts.each do |post| %>
	<div class="well">
	<h3><%= post.title %></h3>
	<p><%= post.body %></p>
	<%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
	<h5><%=post.user.email%></h5>
	
	</div>


<% end %>

app/views/posts/new.html.erb
<h1> Add Posts </h1>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %> 
		<% @post.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>	
	<p>
	<%= f.label :title %> <br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
	<%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1><%=@post.title %></h1>
<h4><%=@post.user.email%></h4>
<p><%= @post.body %></p>

<hr>
<% if user_signed_in? %>
<%= link_to "Edit", edit_post_path(@post), :class =>'btn btn-default' %>
<%= link_to "Delete",post_path(@post), 
			method: :delete,
			data: {confirm: 'Are you sure?'},
			:class =>'btn btn-danger' %>

<% end %>


</hr>


<%= render 'comments/comments' %>
<%= render 'comments/form' %>